### ISSUE TITLE
Why the push for creating an account?

### ISSUE THREAD

**Issue by erreip** [oliversong/onetimebox#31]
One of my favorite 'features' of OneTimeBox was how quickly I can simply create a box add content and forward the link to someone without any need for sign up or account creating...Why the change?

**Comment by oliversong** [comment]
Hey there- as of Nov. 17th, 2014, Filepicker acquired OneTimeBox. While the open source code here does not have a login form, Filepicker is now in charge of the project and is hosting their own version on the onetimebox.org domain.

There's not much I can do at this point, sorry.

**Comment by erreip** [comment]
Fair enough. Thanks for the reply!
